name: tahlil_kolay
description: Tahlil sonucu ekran görüntüsü analizi
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.2.2
  sqflite: ^2.3.3
  provider: ^6.1.2
  encrypt: ^5.0.3
  path_provider: ^2.1.4
  file_picker: ^8.0.6          # PDF + resim için
  path: ^1.8.3                 # DbService'de join() için
  permission_handler: ^10.4.0  # Runtime izinleri için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/splash.png
